### ISSUE TITLE
Update instructions for SSL?

### ISSUE THREAD

**Issue by ktrue** [tim273/weather_radio_scripts#1]
Hi Tim,
Would you consider updating the instructions to add installation of Icecast 2.4.0+SSL capability to the RPi radio?  The Raspian distribution only has 2.0.0 (no SSL) Icecast, so it has to be compiled from source.
I tried the instructions from https://jksinton.com/articles/rpi-compiling-icecast-support-openssl and was successful in the compilation/replacement of Icecast2.  Unfortunately, the connection results in PR_END_OF_FILE_ERROR trying to connect.

Since Chrome 80+ now suppresses http media on an https connection, it's important to get SSL capability to our streams.
Thanks in advance,
Best regards,
Ken

**Comment by tim273** [comment]
Ok, I set up some instructions on how to do SSL. It's not in the way you describe above, but instead using Nginx as an SSL proxy.  It's actually very simple to do and gets the job done.  

Let me know what you think and if it works for you (if you try it that is).
